### ISSUE TITLE
[backend] fix the database model for user roles

### ISSUE THREAD

**Issue by wolftender** [shilangyu/SE2-CBT#163]
the model is dependent on postgresql array types and cannot be tested using in-memory database

the problem can be possibly resolved by:

- creating a mostly static dictionary table with roles and a many-to-many relationship with users (recommended)
- creating user roles table linking many-to-one arbitrary roles with user
- serializing roles with commas or other delimiters in the database (not recommended)

**Comment by wolftender** [comment]
possibly closed by https://github.com/shilangyu/SE2-CBT/commit/d1abac79e27f34cc71597a939f33efeda7a47846

@shilangyu ?

**Comment by shilangyu** [comment]
Yep

**Comment by shilangyu** [comment]
The first option was implemented, namely

> creating a mostly static dictionary table with roles and a many-to-many relationship with users (recommended)
